version: '3.3'
services:
  server:
    build:
      context: ./server
    env_file:
      - .env
    container_name: babel-node-server
    image: babel-server-image
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - app-network
    volumes: 
      - ./server:/usr/src/app
      - /usr/src/app/node_modules


  frontend:
    build:
      context: ./server/client
    container_name: babel-react-client
    stdin_open: true
    image: babel-frontend-image
    ports:
      - 3000:3000
    depends_on:
      - server
    restart: always
    networks:
      - app-network
    volumes:
      - ./server/client:/usr/src/app
      - /usr/src/app/node_modules

networks:
    app-network:
        driver: bridge

    
